CREATE TABLE IF NOT EXISTS customer (
	id INTEGER generated by default as identity,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	primary key (id),
	unique (email)
);

INSERT INTO customer(name, email) values ('Gabriel', 'gabriel@email.com');
INSERT INTO customer(name, email) values ('Daniel', 'daniel@email.com');
